### ISSUE TITLE
[Bug] Error when try to install because of stable version

### ISSUE THREAD

**Issue by 3x1io** [baidou5/laravel-arpdf#2]
![Screenshot 2024-10-14 at 12 45 49 PM](https://github.com/user-attachments/assets/9143eab4-94de-41bc-8d0e-f5044feaa481)

i tried to install the package but I got this error, can you please check your composer package

**Comment by baidou5** [comment]
thx for show me the error  , pleas us  : composer require baidouabdellah/laravel-arpdf:dev-main

to install ;)

**Comment by 3x1io** [comment]
hi, @baidou5 I open a PR to fix this in docs please check it #3 .
